osx_image: xcode10
language: swift

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

cache:
  bundler: true
  cocoapods: true
  directories:
  - ./build
  - ./Example/Pods
  - ./Example/PredicateFlow.xcworkspace

jobs:
  include:
    - stage: lint
      name: "Code quality"
      script: bundle exec fastlane code_lint
    - stage: lint
      name: "Podspec quality"
      script: bundle exec fastlane podspec_lint
    - stage: test
      name: "Test (Debug)"
      script: bundle exec fastlane test_debug
    - stage: test
      name: "Test (Release)"
      script: bundle exec fastlane test_release

